apiVersion: apps/v1
kind: Deployment
metadata:
  name: avn-k-producer
spec:
  selector:
    matchLabels:
      app: avn-k-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: avn-k-producer
    spec:
      containers:
        - name: avn-k-producer
          image: davidavn/avn-bench-kafka-load-generator:latest
          env:
            - name: AIVEN_TOKEN
              value: ...
            - name: AIVEN_PROJECT
              value: 'david-demo'
            - name: AIVEN_SERVICE
              value: 'kafka-bench'
            - name: AIVEN_TOPIC
              value: 'load-topic'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avn-k-reader
spec:
  selector:
    matchLabels:
      app: avn-k-reader
  replicas: 1
  template:
    metadata:
      labels:
        app: avn-k-reader
    spec:
      containers:
        - name: avn-k-reader
          image: davidavn/avn-bench-kafka-load-reader:latest
          env:
            - name: AIVEN_TOKEN
              value: ...
            - name: AIVEN_PROJECT
              value: 'david-demo'
            - name: AIVEN_SERVICE
              value: 'kafka-bench'
            - name: AIVEN_TOPIC
              value: 'load-topic'
